apiVersion: v1 
kind: Pod
metadata:
  name: empty-demo
spec:
  containers:
    - name: centos
      image: centos:7 
      command: ["sleep", "10000"] 
      volumeMounts:
        - name:  data
          mountPath:  /data 
  volumes:
    - name: data
      emptyDir: {}
