

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: efs-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: manual
---
apiVersion: v1
kind: Pod
metadata:
  name: pod-name
spec:
  containers:
    - name: centos
      image: centos:7
      command: ["sleep","10000"]
      volumeMounts:
        - mountPath: /data
          name: efs-pvc
  volumes:
    - name: efs-pvc
      persistentVolumeClaim:
        claimName: efs-pvc