apiVersion: v1
kind: PersistentVolume
metadata:
  name: efs-persist
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: fs-9b722931.efs.us-west-2.amazonaws.com
    path: "/"

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: efs-persist
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi


---
kind: Pod
apiVersion: v1
metadata:
  name: check-nfs
spec:
  containers:
    - name: centos
      image: centos:7
      command: ["sleep", "10000"]
      volumeMounts:
        - mountPath: "/data"
          name: efs-persist
  volumes:
    - name: efs-persist
      persistentVolumeClaim:
        claimName: efs-persist